<a href="https://colab.research.google.com/github/hafizullah12/Data-Science/blob/master/LInear_Algebra_with_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#import numpy 
import numpy as np 
# Declaring Vectors(one Dimension List)
x = [1, 2, 3]
y = [4, 5, 6]

print(type(x))



<class 'list'>


In [4]:
# This does'nt give the vector addition.
print(x + y)



[1, 2, 3, 4, 5, 6]


In [6]:
# Vector addition using Numpy

z = np.add(x, y)
print(z)
print(type(z))



[5 7 9]
<class 'numpy.ndarray'>


In [7]:
# Vector Cross Product
mul = np.cross(x, y)
print(mul)

[-3  6 -3]


In [9]:
#Vector Dot Product 
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print("x:", x)
print("y:", y)
np.dot(x, y)    


x: [1 2 3 4]
y: [5 6 7 8]


70

In [11]:
#Vector Transpose
print("x:", x)
x.shape = (4, 1)
print("xT:", x)
print("y:", y)
y.shape = (4, 1)
print("yT:", y)


x: [[1]
 [2]
 [3]
 [4]]
xT: [[1]
 [2]
 [3]
 [4]]
y: [[5]
 [6]
 [7]
 [8]]
yT: [[5]
 [6]
 [7]
 [8]]


### Matrix

In [0]:
#initialize matrix
x = np.array([[1, 2], [4, 5]]) 
y = np.array([[7, 8], [9, 10]])


In [19]:
#using add() to add matrices 
print ("The element wise addition of matrix is : ") 
print (np.add(x,y)) 


The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]


In [21]:
#using subtract() to subtract matrices 
print ("The element wise subtraction of matrix is : ") 
print (np.subtract(x,y)) 


The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]


In [23]:
# using multiply() to multiply matrices element wise 
print ("The element wise multiplication of matrix is : ") 
print (np.multiply(x,y))


The element wise multiplication of matrix is : 
[[ 7 16]
 [36 50]]


In [24]:
# using divide() to divide matrices 
print ("The element wise division of matrix is : ") 
print (np.divide(x,y)) 


The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [29]:
# using matmul() to divide matrices 
print ("Matrix Multiplication: ") 
print (np.matmul(x,y))



Matrix Multiplication: 
[[25 28]
 [73 82]]


In [31]:
#Identity Matrix  
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
#inverse Matrix
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print(x) 
print(y)


[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [41]:
#Transpose Matrix 
a = np.array([[1, 2], [3, 4]])
a.transpose()

array([[1, 3],
       [2, 4]])